version: 3.1.0.{build}
image: Visual Studio 2022
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: >-
      nuget restore

build:
  project: C:\projects\dotfeather\src\dotfeather.csproj
  publish_nuget: true

configuration: Release

after_build:
  - nuget pack -Prop Configuration=Release src -OutputDirectory src/bin/Release/

artifacts:
  - path: '**\*.nupkg'
    name: DotFeather

deploy:
  - provider: NuGet
    api_key:
      # Use encrypt tool
      # https://ci.appveyor.com/tools/encrypt
      secure: 1k6f11E9bN8eBIzSz4tDjART0Nk5agF+JvR85X+w8Lb8GgJSJTr2uPlZrM+TyIja
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    description: |
      # 3.1.0

      本バージョンから .NET 6 が必須となります。

      ## 追加
      * `DFMouse` にイベントを追加
        * Click - クリックした
        * ButtonDown - ボタンを押した
        * ButtonUp - ボタンを離した
        * Move - カーソルが移動した
        * Enter - カーソルがウィンドウに入った
        * Leave - カーソルがウィンドウから離れた
      * Vector型に、指定した矩形領域に接しているかを計算する `In()` メソッドを追加

      ## 変更
      * **バックエンドをOpenTK/OpenGL 1ベースからSilk.NET/OpenGL 3に変更**
        * ⚠ DotFeatherだけでなくOpenTKのAPIも併用していた場合、ソースコード互換性は失われます。
      * Disposeされたテクスチャを描画しようと試みた場合、警告を発生させるように
      * `DF.Window.FollowsDpi` プロパティを非推奨に
      * `DF.Window.ActualSize`, `ActualWidth`, `ActualHeight` プロパティへの設定を非推奨に
      * `Ellipse` および `Polygon` の描画（Graphic, Shape) を非推奨に
        * 既に動作しなくなっています

      ## 不具合修正
      * Windows 11およびmacOS Montereyで動作しない問題を修正
      * コンソールが見切れる不具合を修正

      ## 既知の不具合
      * Texture: 特定の状況で大量のテクスチャを読み込んだ際に、途中でテクスチャを正常に読み込めなくなる
      * Audio: 停止にラグがある
      * Input: macOSで日本語入力をすると、入力文字列よりも前に改行が挿入される

    auth_token:
      secure: Cl90a4N9L02nmN2e45TxbRCOGAPa1SnO4A0IF6StuIZvUGz4gFvP+5TlPU70JlPp
    on:
      APPVEYOR_REPO_TAG: true # deploy on tag push only
