version: 3.1.0.{build}
image: Visual Studio 2022
skip_non_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

before_build:
  - ps: >-
      nuget restore

build:
  project: C:\projects\dotfeather\src\dotfeather.csproj
  publish_nuget: true

configuration: Release

after_build:
  - nuget pack -Prop Configuration=Release src -OutputDirectory src/bin/Release/

artifacts:
  - path: '**\*.nupkg'
    name: DotFeather

deploy:
  - provider: NuGet
    api_key:
      # Use encrypt tool
      # https://ci.appveyor.com/tools/encrypt
      secure: 0p+A7xhW2Qex9C3sIr4LXPFBNUCxVd1NPvnKH0Yy6uETIpnSAa5q/DkQtOH9Sy9q
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    artifact: /.*\.nupkg/ # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    description: |
      # 3.1.0-beta.01

      ## 変更

      * 本バージョンからバックエンドがOpenTKからSilk.NETに変更されます。
        * バックエンドの移行に伴い、まだいくつか正常に動作しないコード、既知の不具合があります。
      * APIに破壊的変更はありません。
        * ⚠ DotFeatherだけでなくOpenTKのAPIも併用していた場合、ソースコード互換性は失われます。

      ## 既知の不具合

      * Texture: 特定の状況で大量のテクスチャを読み込んだ際に、途中でテクスチャを正常に読み込めなくなる
      * Graphic: ShapeType.Polygon を描画できない
      * Graphic: ShapeType.Rect を描画できない
      * Audio: 停止にラグがある
      * Input: macOSで日本語入力をすると、入力文字列よりも前に改行が挿入される

    auth_token:
      secure: 1k6f11E9bN8eBIzSz4tDjART0Nk5agF+JvR85X+w8Lb8GgJSJTr2uPlZrM+TyIja
    on:
      APPVEYOR_REPO_TAG: true # deploy on tag push only
